# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /#about
    weight: 10
  # - name: News
  #   url: /#news
  #   weight: 20
  - name: Portfolio
    url: /#publications
    weight: 30
  - name: Experience
    url: /#experience
    weight: 40
  # - name: Talks
  #   url: /#talks
  #   weight: 50
  # - name: Platforms
  #   url: /#platforms
  #   weight: 60
  - name: Resume
    url: uploads/resume.pdf
    weight: 70
  - name: Contact
    url: /#contact
    weight: 80
